// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kspApi.Data;

namespace kspApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kspApi.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Estatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaDeContratacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDeNacimientoBeneficiario")
                        .HasColumnType("datetime2");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompletoBeneficiario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentescoBeneficiario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PuestoDeTrabajo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Salario")
                        .HasColumnType("real");

                    b.Property<string>("SexoBeneficiario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90d10994-3bdd-4ca2-a178-6a35fd653c59"),
                            Estatus = true,
                            FechaDeContratacion = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaDeNacimientoBeneficiario = new DateTime(1967, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Foto = "https://scontent-dub4-1.xx.fbcdn.net/v/t1.6435-9/84139256_523628248534229_3398780270420164608_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=88KGS473T_wAX_6cTJf&_nc_ht=scontent-dub4-1.xx&oh=00_AfC-mtqoUJWBizOfE-Q9u3V17qtcl8tct9gb-IE4HeXy-g&oe=63E78073",
                            NombreCompleto = "Luis David Chávez Grimaldo",
                            NombreCompletoBeneficiario = "Francisco Chávez Blanco",
                            ParentescoBeneficiario = "Padre",
                            PuestoDeTrabajo = "Software Enginner",
                            Salario = 12000f,
                            SexoBeneficiario = "Masculino"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
